server:
  port: 8081
  max-http-header-size: 10MB

spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/storage
    password: root

  # Kafka Listener Topic
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage
    topic:
      name:
        registered:
          user: registered-user-topic-for-authentication-service
    group:
      id: group-id
    producer:
      bootstrap-servers: localhost:9092

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF
