server:
  port: 8080
  max-http-header-size: 10MB

#MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/storage
    password: root
  kafka:
    partitions: 3
    topic:
      name: registered-user-profile-topic
    replicas: 1
    producer:
      bootstrap-servers: localhost:9092

#Feign
profile:
  endpoint: /
  service:
    feign:
      client:
        name: Profile-Service
    url: http://localhost:8081
