server:
  port: 8081
  max-http-header-size: 10MB

spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/storage
    password: root

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF
