server:
  port: 8080
  max-http-header-size: 10MB

spring:
  #Mongo
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017/storage
      database: storage
  #Kafka
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage
    producer:
      bootstrap-servers: localhost:9092
    topic:
      name:
        registered:
          user: registered-user-topic
        post:
          publication: post-publication-topic
          comment: post-comment-topic
        delete:
          post: delete-post-topic
        edit:
          post: edit-post-topic
    partitions: 3
    replicas: 1
    group:
      id: group-id

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF

#Feign Login service
login:
  endpoint: /
  service:
    feign:
      client:
        name: Login-Service
    url: http://localhost:8081

#Feign Post service
post:
  find:
    all: /author/posts
    one: /post
  author:
    posts:
      count: /author/posts/count
  service:
    feign:
      client:
        name: Post-Service
    url: http://localhost:8082

#Feign Reaction service
reaction:
  find:
    likes:
      count: /post/likes
    dislikes:
      count: /post/dislikes
    stars:
      count: /post/stars
  service:
    feign:
      client:
        name: Reaction-Service
    url: http://localhost:8084

#Feign Relationship service
relationship:
  find:
    friends:
      count: /profile/friends/count
  service:
    feign:
      client:
        name: Relationship-Service
    url: http://localhost:8083

#Feign Image service
image:
  service:
    feign:
      client:
        name: Image-Service
    url: http://localhost:8085
  profile: /profile-image
  background: /profile-background-image