server:
  port: 8083
  max-http-request-header-size: 10MB

spring:
  application:
    name: profile

  mongodb:
    uri: mongodb://rootuser:rootpass@profile-mongo:27017/storage?authSource=admin
    auto-index-creation: true

  kafka:
    bootstrap-servers: kafka:19092
    group-id: profile-service-group
    partitions: 3
    replicas: 1
    trusted-packages: com.join_in.kafka_models.messages
    offset-reset: earliest
    topic:
      new-registered-user-info: new-registered-user-info

#Identity service Feign client
identity:
  service:
    feign:
      client:
        name: Identity-service-Feign-client
    url:  http://identity-service:8082