server:
  port: 8080
  max-http-header-size: 10MB

spring:
  #Mongo
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017/storage
      database: storage
  #Kafka
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage
    producer:
      bootstrap-servers: localhost:9092
    topic:
      name:
        registered:
          user: registered-user-topic-for-authentication-service
    partitions: 3
    replicas: 1
    group:
      id: group-id

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF

#Feign
post:
  endpoint: /
  service:
    feign:
      client:
        name: Post-Service
    url: http://localhost:8082

login:
  endpoint: /
  service:
    feign:
      client:
        name: Login-Service
    url: http://localhost:8081