services:

  reaction-neo4j:
    image: neo4j:5.26.28
    container_name: neo4j-reaction-service
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/reactionpass
    volumes:
      - reaction-neo4j-data:/data
    networks:
      - join-in-network

  # Executes init.cypher after Neo4j starts
  reaction-neo4j-init:
    image: neo4j:5.26.28
    container_name: neo4j-reaction-init
    restart: "no"
    depends_on:
      - reaction-neo4j
    volumes:
      - ./src/main/resources/neo4j/init.cypher:/scripts/init.cypher:ro
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        set -e

        until cypher-shell -a bolt://reaction-neo4j:7687 -u neo4j -p reactionpass -d neo4j "RETURN 1;" >/dev/null 2>&1; do
          echo "Waiting for Neo4j..."
          sleep 2
        done

        echo "Neo4j is ready. Importing sample data..."

        cypher-shell \
          -a bolt://reaction-neo4j:7687 \
          -u neo4j \
          -p reactionpass \
          -d neo4j \
          --file /scripts/init.cypher

        echo "Sample data imported successfully."
    networks:
      - join-in-network

  reaction-service:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - maven_settings
    container_name: reaction-service
    restart: always
    ports:
      - 8085:8085
    environment:
      SPRING_NEO4J_URI: bolt://reaction-neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: reactionpass
    depends_on:
      - reaction-neo4j
    networks:
      - join-in-network

networks:
  join-in-network:
    external: true

volumes:
  reaction-neo4j-data:

secrets:
  maven_settings:
    file: C:/Users/Иван/.m2/settings.xml