server:
  port: 8080
  max-http-header-size: 10MB

spring:
  #Kafka
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage
    producer:
      bootstrap-servers: localhost:9092
    topic:
      name:
        registered:
          user: registered-user
        post:
          publication: post-publication
          comment: post-comment
        delete:
          post: delete-post
        edit:
          post: edit-post
        like:
          post: like-post
          comment: like-comment
        dislike:
          post: dislike-post
          comment: dislike-comment
        star:
          post: star-post
        accept:
          friendship: accept-friendship
        decline:
          friendship: decline-friendship
        unfriend: unfriend-topic
        user:
          logout: user-logout
        new:
          chat:
            message: new-chat-message
    partitions: 3
    replicas: 1
    group:
      id: group-id

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF

#Feign Login service
gateway:
  service:
    feign:
      client:
        name: API-Gateway-Service
    url: http://localhost:8081
  login:
    endpoint: /api/login
  logout:
    endpoint: /api/logout
  register:
    endpoint: /api/register
  profile:
    endpoint: /api/profile/{identity}

##Feign Post service
#post:
#  find:
#    all: /author/posts
#    one: /post
#  author:
#    posts:
#      count: /author/posts/count
#  user:
#    feed:
#      posts: /user/feed/posts
#  service:
#    feign:
#      client:
#        name: Post-Service
#    url: http://localhost:8082
#
##Feign Relationship service
#relationship:
#  find:
#    friends:
#      count: /profile/friends/count
#      for:
#        user: /profile/friends
#    friend:
#      suggestions: /profile/friend/suggestions
#    friendship:
#      requests:
#        for:
#          user: /profile/friendship/requests
#        count: /profile/friendship/requests/count
#  service:
#    feign:
#      client:
#        name: Relationship-Service
#    url: http://localhost:8083
#
##Feign Image service
#image:
#  service:
#    feign:
#      client:
#        name: Image-Service
#    url: http://localhost:8085
#  profile: /profile-image
#  background: /profile-background-image
#album:
#  images: /profile-album-images
#
##Feign Notification service
#notification:
#  service:
#    feign:
#      client:
#        name: Notification-Service
#    url: http://localhost:8086
#user:
#  notifications: /user/notifications
#
##Feign Message service
#message:
#  service:
#    feign:
#      client:
#        name: Message-Service
#    url: http://localhost:8087
#friends:
#  online: /friends/online
#direct:
#  chat:
#    history: /direct-chat/history
#group:
#  chat:
#    history: /group-chat/history