version: '3.5'

services:

  # Spring boot application
  profile-service:
    container_name: profile-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - profile-service-network
    restart: on-failure

# Docker containers network (name attribute is needed!)
networks:
  profile-service-network:
    name: profile-service-network
    driver: bridge