services:

  # MongoDB
  profile-mongo:
    image: mongo:6.0
    container_name: mongo-profile-service
    volumes:
      - ./src/main/resources/mongo/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=storage
    networks:
      - join-in-network

  # Mongo Express web tool
  profile-mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express-profile-service
    restart: always
    depends_on:
      - profile-mongo
    ports:
      - 9091:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_URL=mongodb://rootuser:rootpass@profile-mongo:27017/
    networks:
      - join-in-network

  # Profile service
  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - maven_settings
    container_name: profile-service
    ports:
      - 8083:8083
    depends_on:
      - profile-mongo
    networks:
      - join-in-network

networks:
  join-in-network:
    external: true

secrets:
  maven_settings:
    file: C:/Users/Иван/.m2/settings.xml