server:
  port: 8086

spring:

  #Mongo
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27019/storage
      database: storage

  #Kafka
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage
    topic:
      name:
        like:
          notification: like-post-notification-topic
        dislike:
          notification: dislike-post-notification-topic
        star:
          notification: star-post-notification-topic
        new:
          user: new-user-topic
          post:
            notification: new-post-notification
          comment:
            notification: new-comment-notification
    group:
      id: group-id

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF