server:
  port: 8084

spring:
  data:
    neo4j:
      uri: bolt://localhost:7688
      username: neo4j
      password: Root_123

  # Kafka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage
    topic:
      name:
        new:
          user: new-user-topic
          post:
            node: new-post-node
          comment:
            node: new-comment-node
        delete:
          nodes: delete-nodes-topic
        like:
          post: like-post-topic
            notification: like-post-notification-topic
        dislike:
          post: dislike-post-topic
            notification: dislike-post-notification-topic
        star:
          post: star-post-topic
            notification: star-post-notification-topic
    group:
      id: group-id

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF

#Feign Post service
post:
  service:
    url: http://localhost:8082
    feign:
      client:
        name: Post-Service
  comments:
    authors: /post/comments/authors