server:
  port: 8081
  max-http-header-size: 10MB

spring:
  application:
    name: gateway
  kafka:
    bootstrap-servers: kafka:19092
    partitions: 3
    replicas: 1
    topic:
      register-new-user: register-new-user

#Identity service Feign client
identity:
  service:
    feign:
      client:
        name: Identity-service-Feign-client
    url:  http://identity-service:8082

#Media service Feign client
media:
  service:
    feign:
      client:
        name: Media-service-Feign-client
    url:  http://media-service:8090