server:
  port: 8081
  max-http-request-header-size: 10MB

spring:
  application:
    name: gateway
  kafka:
    bootstrap-servers: kafka:19092
    partitions: 3
    replicas: 1
    topic:
      register-new-user: register-new-user

#Identity service Feign client
identity:
  service:
    feign:
      client:
        name: Identity-service-Feign-client
    url:  http://identity-service:8082

#Media service Feign client
media:
  service:
    feign:
      client:
        name: Media-service-Feign-client
    url:  http://media-service:8090

#Profile service Feign client
profile:
  service:
    feign:
      client:
        name: Profile-service-Feign-client
    url:  http://profile-service:8083

#Relationship service Feign client
relationship:
  service:
    feign:
      client:
        name: Relationship-service-Feign-client
    url:  http://relationship-service:8087

#Post service Feign client
post:
  service:
    feign:
      client:
        name: Post-service-Feign-client
    url:  http://post-service:8084

#Group service Feign client
group:
  service:
    feign:
      client:
        name: Group-service-Feign-client
    url:  http://group-service:8088

#Reaction service Feign client
reaction:
  service:
    feign:
      client:
        name: Reaction-service-Feign-client
    url:  http://reaction-service:8085

#Search service Feign client
search:
  service:
    feign:
      client:
        name: Search-service-Feign-client
    url:  http://search-service:8092

#Notification service Feign client
notification:
  service:
    feign:
      client:
        name: Notification-service-Feign-client
    url:  http://notification-service:8086