server:
  port: 8082
  max-http-header-size: 10MB

spring:
  application:
    name: identity

  mongodb:
    uri: mongodb://rootuser:rootpass@identity-mongo:27017/storage?authSource=admin
    auto-index-creation: true

  kafka:
    bootstrap-servers: kafka:19092
    group-id: groupId
    partitions: 3
    replicas: 1
    trusted-packages: com.join_in.kafka_models.messages
    offset-reset: earliest
    topic:
      register-new-user: register-new-user
      new-registered-user-info: new-registered-user-info

