server:
  port: 8087

spring:

  #Mongo
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27021/storage
      database: storage

  #Kafka
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF

#Feign Relationship service
relationship:
  service:
    url: http://localhost:8083
    feign:
      client:
        name: Relationship-Service
  find:
    profile:
      friends:
        identities: /profile/friends/identities