server:
  port: 8091
  max-http-request-header-size: 10MB

spring:
  application:
    name: message

  kafka:
    bootstrap-servers: kafka:19092
    group-id: search-service-group
    partitions: 3
    replicas: 1
    trusted-packages: com.join_in.kafka_models.messages
    offset-reset: earliest
    topic:
      new-registered-user-info: new-registered-user-info

  cassandra:
    contact-points: message-cassandra
    port: 9042
    keyspace-name: message_service
    local-datacenter: datacenter1
    schema-action: NONE

  data:
    redis:
      host: message-redis
      port: 6379

#Media service Feign client
media:
  service:
    feign:
      client:
        name: Media-service-Feign-client
    url:  http://media-service:8090

#Profile service Feign client
profile:
  service:
    feign:
      client:
        name: Profile-service-Feign-client
    url:  http://profile-service:8083