server:
  port: 8088

spring:

  #Mongo
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27021/storage
      database: storage

  #Kafka
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage
    topic:
      name:
        user:
          login: user-login
          logout: user-logout
        new:
          chat:
            message: new-chat-message
    group:
      id: group-id

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF