server:
  port: 8082

spring:

  # Redis
  redis:
    password: root
    host: localhost
    port: 6379

  #Mongo
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27020/storage
      database: storage

  #Kafka
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      key:
        type:
          packages: '*'
      value:
        type:
          packages: com.social.kafka.messages.contract.KafkaMessage
    topic:
      name:
        post:
          publication: post-publication-topic-for-post-service
    group:
      id: group-id

#Exclude Kafka logging
logging:
  level:
    org.apache: OFF