server:
  port: 8084
  max-http-request-header-size: 10MB

spring:
  application:
    name: post

#Media service Feign client
media:
  service:
    feign:
      client:
        name: Media-service-Feign-client
    url:  http://media-service:8090

#Profile service Feign client
profile:
  service:
    feign:
      client:
        name: Profile-service-Feign-client
    url:  http://profile-service:8083