server:
  port: 8084
  max-http-request-header-size: 10MB

spring:
  application:
    name: post

  cassandra:
    contact-points: post-cassandra
    port: 9042
    keyspace-name: post_service
    local-datacenter: datacenter1
    schema-action: NONE

#Media service Feign client
media:
  service:
    feign:
      client:
        name: Media-service-Feign-client
    url:  http://media-service:8090

#Profile service Feign client
profile:
  service:
    feign:
      client:
        name: Profile-service-Feign-client
    url:  http://profile-service:8083

#Reaction service Feign client
reaction:
  service:
    feign:
      client:
        name: Reaction-service-Feign-client
    url:  http://reaction-service:8085