version: '3.5'

services:

  # MongoDB
  mongo:
    image: mongo:6.0
    container_name: mongo-message-service
    volumes:
      - ./src/main/resources/mongo/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27021:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=storage

  # Mongo Express web tool
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express-message-service
    restart: always
    depends_on:
      - mongo
    ports:
      - 9095:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_URL=mongodb://rootuser:rootpass@mongo:27017/