server:
  port: 8090
  max-http-header-size: 10MB

spring:
  application:
    name: media

  mongodb:
    uri: mongodb://rootuser:rootpass@media-mongo:27017/storage?authSource=admin
    auto-index-creation: true

  kafka:
    bootstrap-servers: kafka:19092
    group-id: media-service-group
    partitions: 3
    replicas: 1
    trusted-packages: com.join_in.kafka_models.messages
    offset-reset: earliest
    topic:
      new-registered-user-info: new-registered-user-info

aws:
  s3:
    bucket: join-in-media-service-bucket
    region: eu-central-1