CREATE TABLE types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE tags
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE devices
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE plugins
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity         VARCHAR(200) NOT NULL UNIQUE,
    name             VARCHAR(100) NOT NULL UNIQUE,
    creator_identity VARCHAR(200) NOT NULL,
    device_id        INTEGER      NOT NULL,
    type_id          INTEGER      NOT NULL,
    tag_id           INTEGER      NOT NULL,
    description      TEXT         NOT NULL,
    upload_date      DATE         NOT NULL,

    CONSTRAINT pk_plugins_devices
        FOREIGN KEY (device_id)
            REFERENCES devices (id),

    CONSTRAINT pk_plugins_types
        FOREIGN KEY (type_id)
            REFERENCES types (id),

    CONSTRAINT pk_plugins_tags
        FOREIGN KEY (tag_id)
            REFERENCES tags (id)
);

CREATE TABLE versions
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity       VARCHAR(200) NOT NULL UNIQUE,
    name           VARCHAR(200) NOT NULL,
    plugin_id      INTEGER      NOT NULL,
    upload_date    DATE         NOT NULL,
    download_count INTEGER DEFAULT 0,

    CONSTRAINT pk_versions_plugins
        FOREIGN KEY (plugin_id)
            REFERENCES plugins (id)
);