server:
  port: 8092
  max-http-header-size: 10MB

spring:
  application:
    name: search

  mongodb:
    uri: mongodb://rootuser:rootpass@search-mongo:27017/storage?authSource=admin
    auto-index-creation: true

  kafka:
    bootstrap-servers: kafka:19092
    group-id: search-service-group
    partitions: 3
    replicas: 1
    trusted-packages: com.join_in.kafka_models.messages
    offset-reset: earliest
    topic:
      new-registered-user-info: new-registered-user-info